let name = "Leandra";
let sumNumbers = 4 + 4 ;
let sumStrings = "string1" + "string2";
let addition = 1 + 1;
let substraction = 5 - 3;
let multiplication = 5 * 3;
let division = 8 / 4;
let modulus = 8 % 3;
let age = "achtendertig";
console.log(name);
console.log(sumNumbers);
console.log(sumStrings);
console.log(addition);
console.log(substraction);
console.log(multiplication);
console.log(division);
console.log(modulus);
console.log(typeof(age));